### ISSUE TITLE
Event.fromJson isn't expecting a subscriptionId !!

### ISSUE THREAD

**Issue by mufarrah** [ethicnology/dispute#4]
Hi , 

found out that Event.fromJson isnt expecting a subscriptionId which i believe is causing the error !! 

![Screenshot 2023-02-03 011656](https://user-images.githubusercontent.com/67714308/216462475-66d0ebb0-707b-46c5-a387-283b927621f7.png)

**Comment by ethicnology** [comment]
@mufarrah 
The latest version of [dart-nostr](https://github.com/ethicnology/dart-nostr) is 1.3.2 which include the `subscriptionId` when you use [deserialize an event](https://github.com/ethicnology/dart-nostr/blob/main/lib/src/event.dart#L134).

In dispute client the current version is still the 1.0.0 of dart-nostr.

After reviewing your UI changes I will upgrade to the latest dart-nostr which will handle the subscription ID

**Comment by mufarrah** [comment]
> @mufarrah The latest version of [dart-nostr](https://github.com/ethicnology/dart-nostr) is 1.3.2 which include the `subscriptionId` when you use [deserialize an event](https://github.com/ethicnology/dart-nostr/blob/main/lib/src/event.dart#L134).
> 
> In dispute client the current version is still the 1.0.0 of dart-nostr.
> 
> After reviewing your UI changes I will upgrade to the latest dart-nostr which will handle the subscription ID

perfect, let me know if you want me to help

**Comment by ethicnology** [comment]
Fixed in 9d47a0c49750ce46407f7138a3466e776470143c
